### ISSUE TITLE
Yarn imports a different System.Numerics assembly which causes ambiguity with the default System.Numerics.

### ISSUE THREAD

**Issue by CantyCanadian** [YarnSpinnerTool/YarnSpinner-Godot#20]
While most people would use the Godot-provided Numerics classes like Vector2/3/4, some other ported packaged like ImGui still relies on the default .NETCore Numerics, causing a very difficult to fix ambiguity issue.

![image](https://github.com/YarnSpinnerTool/YarnSpinner-Godot/assets/7960042/0e9a3ec2-8db8-4fc6-a370-949c1147a98f)
![image](https://github.com/YarnSpinnerTool/YarnSpinner-Godot/assets/7960042/895cde22-30b1-4697-bcf8-700e37598544)

**Comment by CantyCanadian** [comment]
This is also the case with System.Buffers, so I assume a lot of DLLs are similar.

However, deleting the Yarn versions seem to do the trick, as they have the default DLLs to fall back onto.

**Comment by dogboydog** [comment]
Hey thanks for the report. I think there was a reason the DLLs were repackaged this way in the Unity integration, but  it was probably Unity specific (maybe something about assembly definitions). I can test removing them in the Godot version and make sure there aren't any problems.

**Comment by dogboydog** [comment]
Try out #21  please when you get a chance and let me know. 

Notes from testing locally: 
System.Buffers, System.Reflection.TypeExtensions,  and System.Numerics removed fine without editor or runtime errors 

Removing System.Memory DLL caused: 

error CS0012: The type 'ReadOnlySequence<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Yarn.System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=null'. [C:\Users\chris\YarnSpinner-Godot\YarnSpinner-Godot.csproj]
 
Compiler.Services.Unsafe could also not be removed :
  Error updating YarnProject 'res://Samples/Space/Dialogue/SpaceYarnProject.tres': Could not load file or assembly 'Yarn.System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.   at Google.Protobuf.CodedOutputStream.Dispose()
  
  So I only removed the DLLs that did not cause errors upon removal.
