### ISSUE TITLE
Last line of text not working

### ISSUE THREAD

**Issue by alex-dearden** [YarnSpinnerTool/YarnSpinner-Godot#22]
Even using the `DefaultDialogueSystem.tscn` the last line of dialogue does not show. 

You can create a new label and set that as the last line of dialog but it will not be hidden when the main dialogue runs. 

Expectation:

Last line of text shows when option buttons show.

**Comment by dogboydog** [comment]
Thanks for the report. I will take a look when I can.

**Comment by dogboydog** [comment]
Try #23 . Fixed for me
