### ISSUE TITLE
Upgrade to 4.2

### ISSUE THREAD

**Issue by wadlo** [YarnSpinnerTool/YarnSpinner-Godot#29]
The example currently uses 4.1. I'm not sure if it's a lot of work to upgrade to 4.2 or not, but that's the latest stable release.

**Comment by dogboydog** [comment]
It should be doable. It only affects the sample projects basically with the exception of a warning about EditorInterface and the CI in #28 tests with both 4.1 and 4.2,and has a change behind an #ifdef to address the warning. I'll take a look at updating the engine version of the samples in that PR tonight. If you have a chance to test the changes in that PR by the way, let me know any feedback. Thank you

**Comment by wadlo** [comment]
Opened up a PR https://github.com/YarnSpinnerTool/YarnSpinner-Godot/pull/30
I didn't see any issues in the demos, but maybe I missed something.

**Comment by wadlo** [comment]
PR was merged, so closing this issue. Y'all are fast!

**Comment by dogboydog** [comment]
Thanks for the contribution. i had tested 4.2 locally without committing so I was confident it would work. I also use 4.2 for my game project using YarnSpinner and haven't seen any issues with the changes in #28  . Pulled the update into #28 as well

Thank you
